---
# yamllint disable rule:line-length
image: docker:stable

services:
  - docker:dind

stages:
  - build
  - test
  - deploy

build:
  stage: build
  image: danihodovic/gitlab-runner
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - task build-images
    - task push-images

test:
  stage: test
  image: danihodovic/gitlab-runner
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker-compose pull
    - task lint-py
    - task lint-js
    - task test

deploy: &deploy
  stage: deploy
  only:
    refs:
      - master
  image: danihodovic/ansible
  environment:
    name: production
    url: https://mysite.com
  variables:
    ANSIBLE_CONFIG: ./ansible.cfg  # https://github.com/ansible/ansible/issues/42388
  script:
    - echo Deploying

deploy_manual:
  <<: *deploy
  only:
  when: manual
  stage: test
